backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

logo_url: "/assets/logo.png"

collections:
  - name: "events"
    label: "Veranstaltungen"
    files:
      - file: "content/events.json"
        label: "Veranstaltungen (Liste)"
        name: "events"
        fields:
          - label: "Veranstaltungen"
            name: "items"
            widget: "list"
            collapsed: true
            fields:
              - { label: "Titel", name: "title", widget: "string" }
              - label: "Kategorie"
                name: "category"
                widget: "select"
                options:
                  - { label: "Clubmeeting", value: "clubmeeting" }
                  - { label: "Private Charity", value: "private-charity" }
                  - { label: "Club Charity", value: "club-charity" }
                  - { label: "Organisatorisches", value: "orga" }
              - { label: "Start (Datum/Zeit)", name: "start", widget: "datetime", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mm:00" }
              - { label: "Ende (optional)", name: "end", widget: "datetime", required: false, time_format: "HH:mm", format: "YYYY-MM-DDTHH:mm:00" }
              - { label: "Ort", name: "location", widget: "string", required: false }
              - { label: "Beschreibung", name: "description", widget: "text", required: false }
              - { label: "Anmelde-Link (extern)", name: "rsvp_link", widget: "string", required: false }
              - { label: "Kapazität (optional)", name: "capacity", widget: "number", required: false, min: 0 }
              - { label: "Bild (optional)", name: "cover_image", widget: "image", required: false }

  - name: "orga"
    label: "Organisatorisches"
    files:
      - file: "content/orga.json"
        label: "Orga-Einträge"
        name: "orga"
        fields:
          - label: "Listen"
            name: "lists"
            widget: "list"
            fields:
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Beschreibung", name: "description", widget: "text", required: false }
              - label: "Einträge"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Name",  name: "name",  widget: "string" }
                  - { label: "Beitrag/Bestellung", name: "contribution", widget: "string", required: false }
                  - { label: "Bestellung (optional)", name: "order", widget: "string", required: false }
            
  - name: "meetings"
    label: "Clubmeetings"
    files:
      - file: "content/meetings.json"
        label: "Clubmeetings (Liste)"
        name: "meetings"
        fields:
          - label: "Meetings"
            name: "items"
            widget: "list"
            collapsed: true
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Datum/Zeit (ISO)", name: "datetime", widget: "datetime", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mm:00"}
              - {label: "Ort", name: "location", widget: "string", required: false}
              - {label: "Beschreibung", name: "description", widget: "text", required: false}
              - {label: "Kapazität", name: "capacity", widget: "number", required: false, min: 0}

  - name: "activities"
    label: "Aktivitäten"
    files:
      - file: "content/activities.json"
        label: "Aktivitäten (Liste)"
        name: "activities"
        fields:
          - label: "Aktivitäten"
            name: "items"
            widget: "list"
            collapsed: true
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Datum/Zeit (ISO)", name: "datetime", widget: "datetime", time_format: "HH:mm", format: "YYYY-MM-DDTHH:mm:00"}
              - {label: "Ort", name: "location", widget: "string", required: false}
              - {label: "Beschreibung", name: "description", widget: "text", required: false}
              - {label: "Kapazität", name: "capacity", widget: "number", required: false, min: 0}

  - name: "chronicle"
    label: "Clubchronik"
    files:
      - file: "content/chronicle.json"
        label: "Einträge"
        name: "chronicle"
        fields:
          - label: "Einträge"
            name: "items"
            widget: "list"
            fields:
              - {label: "Jahr", name: "year", widget: "number"}
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Text", name: "text", widget: "text", required: false}

  - name: "downloads"
    label: "Downloads"
    files:
      - file: "content/downloads.json"
        label: "Dokumente"
        name: "downloads"
        fields:
          - label: "Dateien"
            name: "items"
            widget: "list"
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Link/Datei-URL", name: "href", widget: "string"}
